apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-cache-app
  labels:
    app: user-cache-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-cache-app
  template:
    metadata:
      labels:
        app: user-cache-app
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.35
          command: [ 'sh', '-c', 'until nc -z redis 6379; do echo "Waiting for Redis..."; sleep 2; done;' ]
      containers:
        - name: user-cache-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: user-cache-app
spec:
  type: NodePort
  selector:
    app: user-cache-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005
